apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1.kubeprovenance.cloudark.io
spec:
  insecureSkipTLSVerify: true
  group: kubeprovenance.cloudark.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: provenance
  version: v1
