apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-provenance-apiserver
  namespace: provenance
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: kube-provenance-apiserver
        image: kube-crdprovenance-apiserver:latest
        imagePullPolicy: Never
        command: [ "/kube-crdprovenance-apiserver", "--etcd-servers=http://localhost:2379"]
      - name: etcd
        image: quay.io/coreos/etcd:v3.2.18
